export const ADD_STUDENT = "ADD_STUDENT";
export const SET_STUDENT_LIST = "SET_STUDENT_LIST";
export const SET_LOADING = "SET_LOADING";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const SET_TOTAL_PAGE = "SET_TOTAL_PAGE";
export const VISIBLE_CREATE_USER = "VISIBLE_CREATE_USER";
export const TOGGLE_ALERT = "TOGGLE_ALERT";
